import { useCallback, useEffect, useState } from 'react';
import { FileText, Plus, Printer, Trash2, ArrowLeft, Sparkles } from 'lucide-react';
import { api } from '../services/api.js';
import { toast } from '../stores/toasts.js';
import { PageHeader, PanelHeader, Badge, ErrorBanner, Spinner, MetricCard } from '../components/Primitives.jsx';
import { Empty, useConfirm } from '../components/ui.jsx';
import { BarList } from '../components/Chart.jsx';
import { dateTime } from '../utils/format.js';

function ReportView({ report, onBack }) {
  const d = report.data;
  const s = d.summary;
  return (
    <div className="space-y-5">
      <div className="flex flex-wrap items-center gap-3 print:hidden">
        <button className="btn btn-ghost" onClick={onBack}><ArrowLeft size={14} /> All reports</button>
        <button className="btn btn-outline ml-auto" onClick={() => window.print()}><Printer size={14} /> Print / Save as PDF</button>
      </div>
      <section className="card p-6">
        <div className="label-caps text-accent-ink">NexLink network health report</div>
        <h2 className="mt-1 font-display text-[22px] font-semibold text-ink">{report.title}</h2>
        <p className="mt-1 text-[12.5px] text-muted">{dateTime(d.from)} → {dateTime(d.to)} · generated by {report.createdBy} · {report.generator}</p>
        <div className="mt-4 flex gap-3 rounded-lg border border-line bg-raised/50 p-4">
          <Sparkles size={16} className="mt-0.5 shrink-0 text-accent-ink" />
          <p className="text-[13px] leading-relaxed text-ink-2">{report.narrative}</p>
        </div>
      </section>
      <div className="grid grid-cols-2 gap-4 xl:grid-cols-5">
        <MetricCard label="Devices" value={s.devices} hint={`${s.simulated} simulated`} />
        <MetricCard label="Avg availability" value={s.avgAvailabilityPct ?? '—'} unit="%" tone={s.avgAvailabilityPct < 95 ? 'amber' : 'green'} hint="Share of expected samples received" />
        <MetricCard label="Alerts" value={s.alertsOpened} tone={s.criticalAlerts ? 'red' : 'green'} hint={`${s.criticalAlerts} critical · ${s.alertsResolved} resolved`} />
        <MetricCard label="Remote sessions" value={s.sessions} hint="Desktop, files and terminal" />
        <MetricCard label="Anomalous devices" value={s.anomalies} tone={s.anomalies ? 'amber' : 'green'} hint="At report time" />
      </div>
      <section className="card overflow-hidden">
        <PanelHeader icon={FileText} title="Per-device summary" />
        <div className="overflow-x-auto">
          <table className="table">
            <thead><tr><th>Device</th><th>Availability</th><th>CPU avg/max</th><th>RAM avg/max</th><th>Latency avg/max</th><th>Loss avg/max</th><th>Traffic</th><th>Anomaly</th></tr></thead>
            <tbody>
              {d.devices.map((r) => (
                <tr key={r.hostname}>
                  <td className="font-semibold">{r.hostname} {r.simulated && <Badge tone="blue">SIM</Badge>}</td>
                  <td className={`mono ${r.availabilityPct < 95 ? 'text-warn' : ''}`}>{r.availabilityPct ?? '—'}%</td>
                  <td className="mono">{r.cpuAvg ?? '—'} / {r.cpuMax ?? '—'}%</td>
                  <td className="mono">{r.ramAvg ?? '—'} / {r.ramMax ?? '—'}%</td>
                  <td className="mono">{r.latencyAvg ?? '—'} / {r.latencyMax ?? '—'} ms</td>
                  <td className="mono">{r.lossAvg ?? '—'} / {r.lossMax ?? '—'}%</td>
                  <td className="mono">{r.trafficGb ?? 0} GB</td>
                  <td>{r.anomaly === 'normal' ? <span className="text-muted">—</span> : <Badge tone="amber">{r.anomaly}</Badge>}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
      <div className="grid gap-5 md:grid-cols-3">
        <section className="card p-4"><div className="label-caps mb-3">Alerts by kind</div>{Object.keys(d.alertsByKind).length ? <BarList items={Object.entries(d.alertsByKind).map(([label, value]) => ({ label, value }))} color="var(--c-gold)" /> : <p className="text-[12px] text-muted">None.</p>}</section>
        <section className="card p-4"><div className="label-caps mb-3">Sessions by kind</div>{Object.keys(d.sessionsByKind).length ? <BarList items={Object.entries(d.sessionsByKind).map(([label, value]) => ({ label, value }))} /> : <p className="text-[12px] text-muted">None.</p>}</section>
        <section className="card p-4"><div className="label-caps mb-3">Sessions by user</div>{Object.keys(d.sessionsByUser).length ? <BarList items={Object.entries(d.sessionsByUser).map(([label, value]) => ({ label, value }))} color="var(--c-primary)" /> : <p className="text-[12px] text-muted">None.</p>}</section>
      </div>
      {d.topAlerts.length > 0 && (
        <section className="card overflow-hidden">
          <PanelHeader icon={FileText} title="Notable alerts" />
          <table className="table"><thead><tr><th>When</th><th>Device</th><th>Severity</th><th>Message</th><th>Status</th></tr></thead>
            <tbody>{d.topAlerts.map((a, i) => (
              <tr key={i}><td className="text-muted">{dateTime(a.openedAt)}</td><td className="font-medium">{a.hostname}</td><td><Badge tone={a.severity === 'critical' ? 'red' : 'amber'}>{a.severity}</Badge></td><td className="whitespace-normal">{a.message}</td><td>{a.status}</td></tr>
            ))}</tbody></table>
        </section>
      )}
    </div>
  );
}

export default function Reports() {
  const [reports, setReports] = useState(null);
  const [open, setOpen] = useState(null);
  const [busy, setBusy] = useState(null);
  const [error, setError] = useState(null);
  const [confirm, dialog] = useConfirm();

  const load = useCallback(() => api.get('/api/reports').then((r) => setReports(r.reports)).catch((e) => setError(e.message)), []);
  useEffect(() => { load(); }, [load]);

  const generate = async (kind) => {
    setBusy(kind);
    try {
      const r = await api.post('/api/reports', { kind }, { timeoutMs: 90_000 });
      setOpen(r.report);
      load();
    } catch (err) {
      toast({ tone: 'danger', title: 'Report failed', message: err.message });
    } finally {
      setBusy(null);
    }
  };
  const view = async (id) => setOpen((await api.get(`/api/reports/${id}`)).report);
  const remove = async (r) => {
    if (!(await confirm({ title: 'Delete report?', message: r.title, confirmLabel: 'Delete', danger: true }))) return;
    await api.delete(`/api/reports/${r._id}`);
    load();
  };

  return (
    <div className="mx-auto max-w-[1480px] p-6">
      {dialog}
      <PageHeader
        icon={FileText}
        eyebrow="Intelligence"
        title="Reports"
        subtitle="Network health summaries built from stored telemetry, alerts and sessions. The summary paragraph is written by the AI when a Groq key is set."
        actions={!open && (
          <>
            <button className="btn btn-outline" disabled={Boolean(busy)} onClick={() => generate('daily')}>{busy === 'daily' ? <Spinner size={14} /> : <Plus size={14} />} Daily report</button>
            <button className="btn btn-primary" disabled={Boolean(busy)} onClick={() => generate('weekly')}>{busy === 'weekly' ? <Spinner size={14} /> : <Plus size={14} />} Weekly report</button>
          </>
        )}
      />
      {error && <ErrorBanner onRetry={load}>{error}</ErrorBanner>}
      {open ? <ReportView report={open} onBack={() => setOpen(null)} /> : (
        <div className="card overflow-hidden">
          {!reports ? <div className="flex justify-center p-10"><Spinner /></div> : reports.length === 0 ? (
            <Empty icon={FileText} title="No reports yet">Generate a daily or weekly report to get a printable summary for the network.</Empty>
          ) : (
            <table className="table">
              <thead><tr><th>Report</th><th>Period</th><th>Summary by</th><th>Created</th><th /></tr></thead>
              <tbody>
                {reports.map((r) => (
                  <tr key={r._id} className="cursor-pointer" onClick={() => view(r._id)}>
                    <td className="font-semibold">{r.title}</td>
                    <td className="text-muted">{dateTime(r.from)} → {dateTime(r.to)}</td>
                    <td><Badge tone={r.generator?.startsWith('groq') ? 'green' : 'neutral'}>{r.generator}</Badge></td>
                    <td className="text-muted">{dateTime(r.createdAt)} by {r.createdBy}</td>
                    <td className="text-right"><button className="btn btn-ghost h-7 w-7 px-0 text-danger" onClick={(e) => { e.stopPropagation(); remove(r); }}><Trash2 size={13} /></button></td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}
    </div>
  );
}
